{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ab3b42eb-9f07-4cbb-a32c-9c3a97d4a14a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup as bs\n",
    "import pymongo\n",
    "from splinter import Browser\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "30a92200-8797-42ca-a9cd-cf482744df8f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def init_browser():\n",
    "    executable_path = {'executable_path': 'C:/Program Files/chromedriver_win32/chromedriver.exe'}\n",
    "    return Browser('chrome', **executable_path, headless=False)\n",
    "\n",
    "def scrape():\n",
    "    browser = init_browser()\n",
    "\n",
    "    #Mars News\n",
    "    url = 'https://redplanetscience.com/'\n",
    "    browser.visit(url)\n",
    "    html = browser.html\n",
    "    soup = bs(html, 'lxml')\n",
    "\n",
    "    title = soup.find('div', class_=\"content_title\")\n",
    "    title_text = title.a.text\n",
    "    title_text = title_text.strip()\n",
    "    news_p = soup.find(\"div\", class_=\"rollover_description_inner\")\n",
    "    news_text = news_p.text\n",
    "    news_text = news_text.strip()\n",
    "\n",
    "    #Featured Photo\n",
    "    url2 = \"https://www.jpl.nasa.gov/spaceimages/?search=&category=Mars\"\n",
    "    browser.visit(url2)\n",
    "    html2 = browser.html\n",
    "    soup2 = bs(html2, 'html.parser')\n",
    "\n",
    "    results = soup2.find(\"ul\", class_=\"articles\")\n",
    "    href = results.find(\"a\",class_='fancybox')['data-fancybox-href']\n",
    "    featured_image_url = 'https://www.jpl.nasa.gov' + href\n",
    "\n",
    "\n",
    "    #Mars Facts\n",
    "    url4 = 'https://space-facts.com/mars/'\n",
    "    facts_table = pd.read_html(url4)\n",
    "    facts_df = facts_table[0]\n",
    "    facts_df.columns = [\"Description\", \"Value\"]\n",
    "    facts_df = facts_df.set_index(\"Description\")\n",
    "    facts_html = facts_df.to_html()\n",
    "\n",
    "    #Mars Hemispheres\n",
    "    url5 = \"https://astrogeology.usgs.gov/search/results?q=hemisphere+enhanced&k1=target&v1=Mars\"\n",
    "    browser.visit(url5)\n",
    "    html4 = browser.html\n",
    "    soup4 = bs(html4, 'html.parser')\n",
    "\n",
    "    titles = soup4.find_all(\"h3\")\n",
    "    for title in titles:\n",
    "        browser.click_link_by_partial_text(\"Hemisphere\")\n",
    "\n",
    "    results4 = soup4.find_all(\"div\", class_=\"description\")\n",
    "    mars_dict={}\n",
    "    hemisphere_image_urls=[]\n",
    "    for result in results4:\n",
    "        link = result.find('a')\n",
    "        img_href = link['href']\n",
    "        title_img = link.find('h3').text\n",
    "        url6 = \"https://marshemisperes.com\" + img_href\n",
    "        browser.visit(url6)\n",
    "        html5 = browser.html\n",
    "        soup5 = bs(html5, 'html.parser')\n",
    "        pic = soup5.find(\"a\", target=\"_blank\")\n",
    "        pic_href = pic['href']\n",
    "        hemisphere_image_urls.append({\"title\":title_img,\"img_url\":pic_href})\n",
    "\n",
    "    #Dictionary of all Mars Info Scraped\n",
    "    mars_info_dict = {\"news_title\":title_text,\"news_text\":news_text,\"featured_image\":featured_image_url,\n",
    "    \"mars_weather\":mars_weather,\"facts_table\":facts_html,\"hemisphere_img\":hemisphere_image_urls}\n",
    "\n",
    "    browser.quit()\n",
    "\n",
    "    return mars_info_dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8f2cc000-da4f-4626-97ac-b2027a7e88d9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
